language: python
python:
  - '3.9'
  - '3.10'
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - echo "skipping tests"
deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    branch: master
  password:
    secure: GQEFPj9dLG677gXQWPnatlEC7GLGx1aJLRI5nqzPj6nO9K0akM66vks9DCwpY6si8/hKBa7ezEtHChHOg/6FUjxJJ+Lhm06utl7bZbzYHfgSSSC01ePXkGI0mSue3tD9YeyJXtICdvxrVKdB+mWxjMlSeVOuw+WJKjv6I9JCAZwfVbnb6CNh8q7UD9iiO8MxqTzyMZpIipyc7eGC34SPjNwGsr432uDc5I4bUj2cpgPMOOf91eENckSs0jz9pxPzRv0yoh7rxHpqFnymzFess/xDORdD16yhPVPnsupW26+g5Vp1THu+1vgJ43ok2JXtBf0Iw2HYAmjf8h8dlh0VTHHARRwKw3/wDTmOm0IBShCWFHDB3IJ4L/cRcKbCDvYIs1eGhzHi0hHyzLmFRxDWamoVZk7yxU04OjJEhXhP3AYzKhnpYeXtcakppfbN0Dfmz5F0uLQp7nXKrEA9CcZZo5suOQtXWhsPwbeiv9xozBro0oHRIZfG5sepHOfbwO/JTQaSp1h5b+87yuCTPKgw0Q85xObdmzsqUenWuiLPpYBpu3saZcXY2d6rGgt5geJIa6TSjI5WZfnGdXeKNQrLnTikMVapT9e4w7RluHol5M9dKflx8BtXWJ8mwa7dsI10Xo0p9GP7FUIpmRiiwlDVHcxta6U5Xuz0WIu2CufSSmA=
